In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/MAPCO2_SAMI.csv')
print(df.columns)

Index(['DeploymentId', 'date', 'time', 'lon', 'lat', 'Temp_5m', 'pCO2_5m',
       'O2_5m', 'Temp_34point5m', 'pCO2_34point5m', 'O2_34point5m', 'Temp_50m',
       'pCO2_50m', 'O2_50m', 'Temp_75m', 'pCO2_75m', 'O2_75m', 'Temp_105m_96m',
       'pCO2_105m_96m', 'O2_105m_96m', 'Temp_1m', 'pH_1m'],
      dtype='object')

In [ ]:
df['date_str'] = df['date'].astype(str)
df['time_str'] = df['time'].astype(str)

# Create a datetime column by combining year, month, day, and time (assuming 'HHMM' format)
df['datetime'] = pd.to_datetime(df['date_str'] + df['time_str'])

# Set desired format with timezone offset (-05:00 in this example)
df['created_at'] = df['datetime'].dt.strftime('%Y-%m-%dT%H:%M:%S+00:00')

# Print the result (excluding unnecessary columns for clarity)
print(df[['created_at']].to_string(index=False))

               created_at
2008-03-09T10:30:00+00:00
2008-03-09T11:00:00+00:00
2008-03-09T11:30:00+00:00
2008-03-09T12:00:00+00:00
2008-03-09T12:30:00+00:00
2008-03-09T13:00:00+00:00
2008-03-09T13:30:00+00:00
2008-03-09T14:00:00+00:00
2008-03-09T14:30:00+00:00
2008-03-09T15:00:00+00:00
2008-03-09T15:30:00+00:00
2008-03-09T16:00:00+00:00
2008-03-09T16:30:00+00:00
2008-03-09T17:00:00+00:00
2008-03-09T17:30:00+00:00
2008-03-09T18:00:00+00:00
2008-03-09T18:30:00+00:00
2008-03-09T19:00:00+00:00
2008-03-09T19:30:00+00:00
2008-03-09T20:00:00+00:00
2008-03-09T20:30:00+00:00
2008-03-09T21:00:00+00:00
2008-03-09T21:30:00+00:00
2008-03-09T22:00:00+00:00
2008-03-09T22:30:00+00:00
2008-03-09T23:00:00+00:00
2008-03-09T23:30:00+00:00
2008-03-01T00:00:00+00:00
2008-03-10T03:00:00+00:00
2008-03-10T10:00:00+00:00
2008-03-10T13:00:00+00:00
2008-03-10T20:00:00+00:00
2008-03-10T23:00:00+00:00
2008-03-10T03:00:00+00:00
2008-03-10T03:30:00+00:00
2008-03-10T04:00:00+00:00
2008-03-10T04:30:00+00:00
2008-03-10T05:00:00+00:00
2008-03-10T05:30:00+00:00
2008-03-10T06:00:00+00:00
2008-03-10T06:30:00+00:00
2008-03-10T07:00:00+00:00
2008-03-10T07:30:00+00:00
2008-03-10T08:00:00+00:00
2008-03-10T08:30:00+00:00
2008-03-10T09:00:00+00:00
2008-03-10T09:30:00+00:00
2008-03-10T10:00:00+00:00
2008-03-10T10:30:00+00:00
2008-03-10T11:00:00+00:00
2008-03-10T11:30:00+00:00
2008-03-10T12:00:00+00:00
2008-03-10T12:30:00+00:00
2008-03-10T13:00:00+00:00
2008-03-10T13:30:00+00:00
2008-03-10T14:00:00+00:00
2008-03-10T14:30:00+00:00
2008-03-10T15:00:00+00:00
2008-03-10T15:30:00+00:00
2008-03-10T16:00:00+00:00
2008-03-10T16:30:00+00:00
2008-03-10T17:00:00+00:00
2008-03-10T17:30:00+00:00
2008-03-10T18:00:00+00:00
2008-03-10T18:30:00+00:00
2008-03-10T19:00:00+00:00
2008-03-10T19:30:00+00:00
2008-03-10T20:00:00+00:00
2008-03-10T20:30:00+00:00
2008-03-10T21:00:00+00:00
2008-03-10T21:30:00+00:00
2008-03-10T22:00:00+00:00
2008-03-10T22:30:00+00:00
2008-03-10T23:00:00+00:00
2008-03-10T23:30:00+00:00
2008-03-01T01:00:00+00:00
2008-03-11T03:00:00+00:00
2008-03-11T10:00:00+00:00
2008-03-11T13:00:00+00:00
2008-03-11T20:00:00+00:00
2008-03-11T23:00:00+00:00
2008-03-11T03:00:00+00:00
2008-03-11T03:30:00+00:00
2008-03-11T04:00:00+00:00
2008-03-11T04:30:00+00:00
2008-03-11T05:00:00+00:00
2008-03-11T05:30:00+00:00
2008-03-11T06:00:00+00:00
2008-03-11T06:30:00+00:00
2008-03-11T07:00:00+00:00
2008-03-11T07:30:00+00:00
2008-03-11T08:00:00+00:00
2008-03-11T08:30:00+00:00
2008-03-11T09:00:00+00:00
2008-03-11T09:30:00+00:00
2008-03-11T10:00:00+00:00
2008-03-11T10:30:00+00:00
2008-03-11T11:00:00+00:00
2008-03-11T11:30:00+00:00
2008-03-11T12:00:00+00:00
2008-03-11T12:30:00+00:00
2008-03-11T13:00:00+00:00
2008-03-11T13:30:00+00:00
2008-03-11T14:00:00+00:00
2008-03-11T14:30:00+00:00
2008-03-11T15:00:00+00:00
2008-03-11T15:30:00+00:00
2008-03-11T16:00:00+00:00
2008-03-11T16:30:00+00:00
2008-03-11T17:00:00+00:00
2008-03-11T17:30:00+00:00
2008-03-11T18:17:00+00:00
2008-03-11T19:00:00+00:00
2008-03-11T19:30:00+00:00
2008-03-11T20:00:00+00:00
2008-03-11T20:30:00+00:00
2008-03-11T21:00:00+00:00
2008-03-11T21:30:00+00:00
2008-03-11T22:00:00+00:00
2008-03-11T22:30:00+00:00
2008-03-11T23:00:00+00:00
2008-03-11T23:30:00+00:00
2008-03-01T02:00:00+00:00
2008-03-12T03:00:00+00:00
2008-03-12T10:00:00+00:00
2008-03-12T13:00:00+00:00
2008-03-12T20:00:00+00:00
2008-03-12T23:00:00+00:00
2008-03-12T03:00:00+00:00
2008-03-12T03:30:00+00:00
2008-03-12T04:00:00+00:00
2008-03-12T04:30:00+00:00
2008-03-12T05:00:00+00:00
2008-03-12T05:30:00+00:00
2008-03-12T06:00:00+00:00
2008-03-12T06:30:00+00:00
2008-03-12T07:00:00+00:00
2008-03-12T07:30:00+00:00
2008-03-12T08:00:00+00:00
2008-03-12T08:30:00+00:00
2008-03-12T09:00:00+00:00
2008-03-13T23:00:00+00:00
2008-03-13T23:30:00+00:00
2008-03-01T04:00:00+00:00
2008-03-14T03:00:00+00:00
2008-03-14T10:00:00+00:00
2008-03-14T13:00:00+00:00
2008-03-14T20:00:00+00:00
2008-03-14T23:00:00+00:00
2008-03-14T03:00:00+00:00
2008-03-14T03:30:00+00:00
2008-03-14T04:00:00+00:00
2008-03-14T04:30:00+00:00
2008-03-14T05:00:00+00:00
2008-03-14T05:30:00+00:00
2008-03-14T06:00:00+00:00
2008-03-14T06:30:00+00:00
2008-03-14T07:00:00+00:00
2008-03-14T07:30:00+00:00
2008-03-14T08:00:00+00:00
2008-03-14T08:30:00+00:00
2008-03-14T09:00:00+00:00
2008-03-14T09:30:00+00:00
2008-03-14T10:00:00+00:00
2008-03-14T10:30:00+00:00
2008-03-14T11:00:00+00:00
2008-03-14T11:30:00+00:00
2008-03-14T12:00:00+00:00
2008-03-14T12:30:00+00:00
2008-03-14T13:00:00+00:00
2008-03-14T13:30:00+00:00
2008-03-14T14:00:00+00:00
2008-03-14T14:30:00+00:00
2008-03-14T15:00:00+00:00
2008-03-14T15:30:00+00:00
2008-03-14T16:00:00+00:00
2008-03-14T16:30:00+00:00
2008-03-14T17:00:00+00:00
2008-03-14T17:30:00+00:00
2008-03-14T18:00:00+00:00
2008-03-14T18:30:00+00:00
2008-03-14T19:00:00+00:00
2008-03-14T19:30:00+00:00
2008-03-14T20:00:00+00:00
2008-03-14T20:30:00+00:00
2008-03-14T21:00:00+00:00
2008-03-14T21:30:00+00:00
2008-03-14T22:00:00+00:00
2008-03-14T22:30:00+00:00
2008-03-14T23:00:00+00:00
2008-03-14T23:30:00+00:00
2008-03-01T05:00:00+00:00
2008-03-15T03:00:00+00:00
2008-03-15T10:00:00+00:00
2008-03-15T13:00:00+00:00
2008-03-15T20:00:00+00:00
2008-03-15T23:00:00+00:00
2008-03-15T03:00:00+00:00
2008-03-15T03:30:00+00:00
2008-03-15T04:00:00+00:00
2008-03-15T04:30:00+00:00
2008-03-15T05:00:00+00:00
2008-03-15T05:30:00+00:00
2008-03-15T06:00:00+00:00
2008-03-15T06:47:00+00:00
2008-03-15T07:30:00+00:00
2008-03-15T08:00:00+00:00
2008-03-15T08:30:00+00:00
2008-03-15T09:00:00+00:00
2008-03-15T09:30:00+00:00
2008-03-15T10:00:00+00:00
2008-03-15T10:30:00+00:00
2008-03-15T11:00:00+00:00
2008-03-15T11:30:00+00:00
2008-03-15T12:00:00+00:00
2008-03-15T12:30:00+00:00
2008-03-15T13:00:00+00:00
2008-03-15T13:30:00+00:00
2008-03-15T14:00:00+00:00
2008-03-15T14:30:00+00:00
2008-03-15T15:00:00+00:00
2008-03-15T15:30:00+00:00
2008-03-15T16:00:00+00:00
2008-03-15T16:30:00+00:00
2008-03-15T17:00:00+00:00
2008-03-15T17:30:00+00:00
2008-03-15T18:00:00+00:00
2008-03-15T18:30:00+00:00
2008-03-15T19:00:00+00:00
2008-03-15T19:30:00+00:00
2008-03-15T20:00:00+00:00
2008-03-15T20:30:00+00:00
2008-03-15T21:00:00+00:00
2008-03-15T21:30:00+00:00
2008-03-15T22:00:00+00:00
2008-03-15T22:30:00+00:00
2008-03-15T23:00:00+00:00
2008-03-15T23:30:00+00:00
2008-03-01T06:00:00+00:00
2008-03-16T03:00:00+00:00
2008-03-16T10:00:00+00:00
2008-03-16T13:00:00+00:00
2008-03-16T20:00:00+00:00
2008-03-16T23:00:00+00:00
2008-03-16T03:00:00+00:00
2008-03-16T03:30:00+00:00
2008-03-16T04:00:00+00:00
2008-03-16T04:30:00+00:00
2008-03-16T05:00:00+00:00
2008-03-16T05:30:00+00:00
2008-03-16T06:00:00+00:00
2008-03-16T06:30:00+00:00
2008-03-16T07:00:00+00:00
2008-03-16T07:30:00+00:00
2008-03-16T08:00:00+00:00
2008-03-16T08:30:00+00:00
2008-03-16T09:00:00+00:00
2008-03-16T09:30:00+00:00
2008-03-16T10:00:00+00:00
2008-03-16T10:30:00+00:00
2008-03-16T11:00:00+00:00
2008-03-16T11:30:00+00:00
2008-03-16T12:00:00+00:00
2008-03-16T12:30:00+00:00
2008-03-16T13:00:00+00:00
2008-03-16T13:30:00+00:00
2008-03-16T14:00:00+00:00
2008-03-16T14:30:00+00:00
2008-03-16T15:00:00+00:00
2008-03-16T15:30:00+00:00
2008-03-16T16:00:00+00:00
2008-03-16T16:30:00+00:00
2008-03-16T17:00:00+00:00
2008-03-16T17:30:00+00:00
2008-03-16T18:00:00+00:00
2008-03-16T18:30:00+00:00
2008-03-16T19:00:00+00:00
2008-03-16T19:30:00+00:00
2008-03-16T20:00:00+00:00
2008-03-16T20:30:00+00:00
2008-03-16T21:00:00+00:00
2008-03-16T21:30:00+00:00
2008-03-16T22:00:00+00:00
2008-03-16T22:30:00+00:00
2008-03-16T23:00:00+00:00
2008-03-16T23:30:00+00:00
2008-03-01T07:00:00+00:00
2008-03-17T03:00:00+00:00
2008-03-17T10:00:00+00:00
2008-03-17T13:00:00+00:00
2008-03-17T20:00:00+00:00
2008-03-17T23:00:00+00:00
2008-03-17T03:00:00+00:00
2008-03-17T03:30:00+00:00
2008-03-17T04:00:00+00:00
2008-03-17T04:30:00+00:00
2008-03-17T05:00:00+00:00
2008-03-17T05:30:00+00:00
2008-03-17T06:00:00+00:00
2008-03-17T06:30:00+00:00
2008-03-17T07:00:00+00:00
2008-03-17T07:30:00+00:00
2008-03-17T08:00:00+00:00
2008-03-17T08:30:00+00:00
2008-03-17T09:00:00+00:00
2008-03-17T09:30:00+00:00
2008-03-17T10:00:00+00:00
2008-03-17T10:30:00+00:00
2008-03-17T11:00:00+00:00
2008-03-17T11:30:00+00:00
2008-03-17T12:00:00+00:00
2008-03-17T12:30:00+00:00
2008-03-17T13:00:00+00:00
2008-03-17T13:30:00+00:00
2008-03-17T14:00:00+00:00
2008-03-17T14:30:00+00:00
2008-03-17T15:00:00+00:00
2008-03-17T15:30:00+00:00
2008-03-17T16:00:00+00:00
2008-03-17T16:30:00+00:00
2008-03-17T17:00:00+00:00
2008-03-17T17:30:00+00:00
2008-03-17T18:00:00+00:00
2008-03-17T18:30:00+00:00
2008-03-17T19:00:00+00:00
2008-03-17T19:30:00+00:00
2008-03-17T20:00:00+00:00
2008-03-17T20:30:00+00:00
2008-03-17T21:00:00+00:00
2008-03-17T21:30:00+00:00
2008-03-17T22:00:00+00:00
2008-03-17T22:30:00+00:00
2008-03-17T23:00:00+00:00
2008-03-17T23:30:00+00:00
2008-03-01T08:00:00+00:00
2008-03-18T03:00:00+00:00
2008-03-18T10:00:00+00:00
2008-03-18T13:00:00+00:00
2008-03-18T20:00:00+00:00
2008-03-18T23:00:00+00:00
2008-03-18T03:00:00+00:00
2008-03-18T03:30:00+00:00
2008-03-18T04:00:00+00:00
2008-03-18T04:30:00+00:00
2008-03-18T05:00:00+00:00
2008-03-18T05:30:00+00:00
2008-03-18T06:00:00+00:00
2008-03-18T06:30:00+00:00
2008-03-18T07:00:00+00:00
2008-03-18T07:30:00+00:00
2008-03-18T08:00:00+00:00
2008-03-18T08:30:00+00:00
2008-03-18T09:00:00+00:00
2008-03-22T13:00:00+00:00
2008-03-22T20:00:00+00:00
2008-03-22T23:00:00+00:00
2008-03-22T03:00:00+00:00
2008-03-22T03:30:00+00:00
2008-03-22T04:00:00+00:00
2008-03-22T04:30:00+00:00
2008-03-22T05:00:00+00:00
2008-03-22T05:30:00+00:00
2008-03-22T06:00:00+00:00
2008-03-22T06:30:00+00:00
2008-03-22T07:00:00+00:00
2008-03-22T07:47:00+00:00
2008-03-22T08:30:00+00:00
2008-03-22T09:00:00+00:00
2008-03-22T09:30:00+00:00
2008-03-22T10:00:00+00:00
2008-03-22T10:30:00+00:00
2008-03-22T11:00:00+00:00
2008-03-22T11:30:00+00:00
2008-03-22T12:00:00+00:00
2008-03-22T12:30:00+00:00
2008-03-22T13:00:00+00:00
2008-03-22T13:30:00+00:00
2008-03-22T14:00:00+00:00
2008-03-22T14:30:00+00:00
2008-03-22T15:00:00+00:00
2008-03-22T15:30:00+00:00
2008-03-22T16:00:00+00:00
2008-03-22T16:30:00+00:00
2008-03-22T17:00:00+00:00
2008-03-22T17:30:00+00:00
2008-03-22T18:00:00+00:00
2008-03-22T18:30:00+00:00
2008-03-22T19:00:00+00:00
2008-03-22T19:30:00+00:00
2008-03-22T20:00:00+00:00
2008-03-22T20:30:00+00:00
2008-03-22T21:00:00+00:00
2008-03-22T21:30:00+00:00
2008-03-22T22:00:00+00:00
2008-03-22T22:30:00+00:00
2008-03-22T23:00:00+00:00
2008-03-22T23:30:00+00:00
2008-03-02T03:00:00+00:00
2008-03-23T03:00:00+00:00
2008-03-23T10:00:00+00:00
2008-03-23T13:00:00+00:00
2008-03-23T20:00:00+00:00
2008-03-23T23:00:00+00:00
2008-03-23T03:00:00+00:00
2008-03-23T03:30:00+00:00
2008-03-23T04:00:00+00:00
2008-03-23T04:30:00+00:00
2008-03-23T05:00:00+00:00
2008-03-23T05:30:00+00:00
2008-03-23T06:00:00+00:00
2008-03-23T06:30:00+00:00
2008-03-23T07:00:00+00:00
2008-03-23T07:30:00+00:00
2008-03-23T08:00:00+00:00
2008-03-23T08:30:00+00:00
2008-03-23T09:00:00+00:00
2008-03-23T09:30:00+00:00
2008-03-23T10:00:00+00:00
2008-03-23T10:30:00+00:00
2008-03-23T11:00:00+00:00
2008-03-23T11:30:00+00:00
2008-03-23T12:00:00+00:00
2008-03-23T12:30:00+00:00
2008-03-23T13:00:00+00:00
2008-03-23T13:30:00+00:00
2008-03-23T14:00:00+00:00
2008-03-23T14:30:00+00:00
2008-03-23T15:00:00+00:00
2008-03-23T15:30:00+00:00
2008-03-23T16:00:00+00:00
2008-03-23T16:30:00+00:00
2008-03-23T17:00:00+00:00
2008-03-23T17:30:00+00:00
2008-03-23T18:00:00+00:00
2008-03-23T18:30:00+00:00
2008-03-23T19:00:00+00:00
2008-03-23T19:30:00+00:00
2008-03-23T20:00:00+00:00
2008-03-23T20:30:00+00:00
2008-03-23T21:00:00+00:00
2008-03-23T21:30:00+00:00
2008-03-23T22:00:00+00:00
2008-03-23T22:30:00+00:00
2008-03-23T23:00:00+00:00
2008-03-23T23:30:00+00:00
2008-03-02T04:00:00+00:00
2008-03-24T03:00:00+00:00
2008-03-24T10:00:00+00:00
2008-03-24T13:00:00+00:00
2008-03-24T20:00:00+00:00
2008-03-24T23:00:00+00:00
2008-03-24T03:00:00+00:00
2008-03-24T03:30:00+00:00
2008-03-24T04:00:00+00:00
2008-03-24T04:30:00+00:00
2008-03-24T05:00:00+00:00
2008-03-24T05:30:00+00:00
2008-03-24T06:00:00+00:00
2008-03-24T06:30:00+00:00
2008-03-24T07:00:00+00:00
2008-03-24T07:30:00+00:00
2008-03-24T08:00:00+00:00
2008-03-24T08:30:00+00:00
2008-03-24T09:00:00+00:00
2008-03-24T09:30:00+00:00
2008-03-24T10:00:00+00:00
2008-03-24T10:30:00+00:00
2008-03-24T11:00:00+00:00
2008-03-24T11:30:00+00:00
2008-03-24T12:00:00+00:00
2008-03-24T12:30:00+00:00
2008-03-24T13:00:00+00:00
2008-03-24T13:30:00+00:00
2008-03-24T14:00:00+00:00
2008-03-24T14:30:00+00:00
2008-03-24T15:00:00+00:00
2008-03-24T15:30:00+00:00
2008-03-24T16:00:00+00:00
2008-03-24T16:30:00+00:00
2008-03-24T17:00:00+00:00
2008-03-24T17:30:00+00:00
2008-03-24T18:00:00+00:00
2008-03-24T18:30:00+00:00
2008-03-24T19:00:00+00:00
2008-03-24T19:30:00+00:00
2008-03-24T20:00:00+00:00
2008-03-24T20:30:00+00:00
2008-03-24T21:00:00+00:00
2008-03-24T21:30:00+00:00
2008-03-24T22:00:00+00:00
2008-03-24T22:30:00+00:00
2008-03-24T23:00:00+00:00
2008-03-24T23:30:00+00:00
2008-03-02T05:00:00+00:00
2008-03-25T03:00:00+00:00
2008-03-25T10:00:00+00:00
2008-03-25T13:00:00+00:00
2008-03-25T20:00:00+00:00
2008-03-25T23:00:00+00:00
2008-03-25T03:00:00+00:00
2008-03-25T03:30:00+00:00
2008-03-25T04:00:00+00:00
2008-03-25T04:30:00+00:00
2008-03-25T05:00:00+00:00
2008-03-25T05:30:00+00:00
2008-03-25T06:00:00+00:00
2008-03-25T06:30:00+00:00
2008-03-25T07:00:00+00:00
2008-03-25T07:30:00+00:00
2008-03-25T08:00:00+00:00
2008-03-25T08:30:00+00:00
2008-03-25T09:00:00+00:00
2008-03-25T09:30:00+00:00
2008-03-25T10:00:00+00:00
2008-03-25T10:30:00+00:00
2008-03-25T11:00:00+00:00
2008-03-25T11:30:00+00:00
2008-03-25T12:00:00+00:00
2008-03-25T12:30:00+00:00
2008-03-25T13:00:00+00:00
2008-03-25T13:30:00+00:00
2008-03-25T14:00:00+00:00
2008-03-25T14:30:00+00:00
2008-03-25T15:00:00+00:00
2008-03-25T15:30:00+00:00
2008-03-25T16:00:00+00:00
2008-03-25T16:30:00+00:00
2008-03-25T17:00:00+00:00
2008-03-25T17:30:00+00:00
2008-03-25T18:00:00+00:00
2008-03-25T18:30:00+00:00
2008-03-25T19:00:00+00:00
2008-03-25T19:30:00+00:00
2008-03-25T20:17:00+00:00
2008-03-25T21:00:00+00:00
2008-03-25T21:30:00+00:00
2008-03-25T22:00:00+00:00
2008-03-25T22:30:00+00:00
2008-03-25T23:00:00+00:00
2008-03-25T23:30:00+00:00
2008-03-02T06:00:00+00:00
2008-03-26T03:00:00+00:00
2008-03-26T10:00:00+00:00
2008-03-26T13:00:00+00:00
2008-03-26T20:00:00+00:00
2008-03-26T23:00:00+00:00
2008-03-26T03:00:00+00:00
2008-03-26T03:30:00+00:00
2008-03-26T04:00:00+00:00
2008-03-26T04:30:00+00:00
2008-03-26T05:00:00+00:00
2008-03-26T05:30:00+00:00
2008-03-26T06:00:00+00:00
2008-03-26T06:30:00+00:00
2008-03-26T07:00:00+00:00
2008-03-26T07:30:00+00:00
2008-03-26T08:00:00+00:00
2008-03-26T08:30:00+00:00
2008-03-26T09:00:00+00:00
2008-03-26T09:30:00+00:00
2008-03-26T10:00:00+00:00
2008-03-26T10:30:00+00:00
2008-03-26T11:00:00+00:00
2008-03-26T11:30:00+00:00
2008-03-26T12:00:00+00:00
2008-03-26T12:30:00+00:00
2008-03-26T13:00:00+00:00
2008-03-26T13:30:00+00:00
2008-03-26T14:00:00+00:00
2008-03-26T14:30:00+00:00
2008-03-26T15:00:00+00:00
2008-03-26T15:30:00+00:00
2008-03-26T16:00:00+00:00
2008-03-26T16:30:00+00:00
2008-03-26T17:00:00+00:00
2008-03-26T17:30:00+00:00
2008-03-26T18:00:00+00:00
2008-03-26T18:30:00+00:00
2008-03-26T19:00:00+00:00
2008-03-26T19:30:00+00:00
2008-03-26T20:00:00+00:00
2008-03-26T20:30:00+00:00
2008-03-26T21:00:00+00:00
2008-03-26T21:30:00+00:00
2008-03-26T22:00:00+00:00
2008-03-26T22:30:00+00:00
2008-03-26T23:00:00+00:00
2008-03-26T23:30:00+00:00
2008-03-02T07:00:00+00:00
2008-03-27T03:00:00+00:00
2008-03-27T10:00:00+00:00
2008-03-27T13:00:00+00:00
2008-03-27T20:00:00+00:00
2008-03-27T23:00:00+00:00
2008-03-27T03:00:00+00:00
2008-03-27T03:30:00+00:00
2008-03-27T04:00:00+00:00
2008-03-27T04:30:00+00:00
2008-03-27T05:00:00+00:00
2008-03-27T05:30:00+00:00
2008-03-27T06:00:00+00:00
2008-03-27T06:30:00+00:00
2008-03-27T07:00:00+00:00
2008-03-27T07:30:00+00:00
2008-03-27T08:00:00+00:00
2008-03-27T08:30:00+00:00
2008-03-27T09:00:00+00:00
2008-03-27T09:30:00+00:00
2008-03-27T10:00:00+00:00
2008-03-27T10:30:00+00:00
2008-03-27T11:00:00+00:00
2008-03-27T11:30:00+00:00
2008-03-27T12:00:00+00:00
2008-03-27T12:30:00+00:00
2008-03-27T13:00:00+00:00
2008-03-27T13:30:00+00:00
2008-03-27T14:00:00+00:00
2008-03-27T14:30:00+00:00
2008-03-27T15:00:00+00:00
2008-03-27T15:30:00+00:00
2008-03-27T16:00:00+00:00
2008-03-27T16:30:00+00:00
2008-03-27T17:00:00+00:00
2008-03-27T17:30:00+00:00
2008-03-27T18:00:00+00:00
2008-03-27T18:30:00+00:00
2008-03-27T19:00:00+00:00
2008-03-27T19:30:00+00:00
2008-03-27T20:00:00+00:00
2008-03-27T20:30:00+00:00
2008-03-27T21:00:00+00:00
2008-03-27T21:30:00+00:00
2008-03-27T22:00:00+00:00
2008-03-27T22:30:00+00:00
2008-03-27T23:00:00+00:00
2008-03-27T23:30:00+00:00
2008-03-02T08:00:00+00:00
2008-03-28T03:00:00+00:00
2008-03-28T10:00:00+00:00
2008-03-28T13:00:00+00:00
2008-03-28T20:00:00+00:00
2008-03-28T23:00:00+00:00
2008-03-28T03:00:00+00:00
2008-03-28T03:30:00+00:00
2008-03-28T04:00:00+00:00
2008-03-28T04:30:00+00:00
2008-03-28T05:00:00+00:00
2008-03-28T05:30:00+00:00
2008-03-28T06:00:00+00:00
2008-03-28T06:30:00+00:00
2008-03-28T07:00:00+00:00
2008-03-28T07:30:00+00:00
2008-03-28T08:00:00+00:00
2008-03-28T08:30:00+00:00
2008-03-28T09:00:00+00:00
2008-03-28T09:30:00+00:00
2008-03-28T10:00:00+00:00
2008-03-28T10:30:00+00:00
2008-03-28T11:00:00+00:00
2008-03-28T11:30:00+00:00
2008-03-28T12:00:00+00:00
2008-03-28T12:30:00+00:00
2008-03-28T13:00:00+00:00
2008-03-28T13:30:00+00:00
2008-03-28T14:00:00+00:00
2008-03-28T14:30:00+00:00
2008-03-28T15:00:00+00:00
2008-03-28T15:30:00+00:00
2008-03-28T16:00:00+00:00
2008-03-28T16:30:00+00:00
2008-03-28T17:00:00+00:00
2008-03-28T17:30:00+00:00
2008-03-28T18:00:00+00:00
2008-03-28T18:30:00+00:00
2008-03-28T19:00:00+00:00
2008-03-28T19:30:00+00:00
2008-03-28T20:00:00+00:00
2008-03-28T20:30:00+00:00
2008-03-28T21:00:00+00:00
2008-03-28T21:30:00+00:00
2008-03-28T22:00:00+00:00
2008-03-28T22:30:00+00:00
2008-03-28T23:00:00+00:00
2008-03-28T23:30:00+00:00
2008-03-02T09:00:00+00:00
2008-03-29T03:00:00+00:00
2008-03-29T10:00:00+00:00
2008-03-29T13:00:00+00:00
2008-03-29T20:00:00+00:00
2008-03-29T23:00:00+00:00
2008-03-29T03:00:00+00:00
2008-03-29T03:30:00+00:00
2008-03-29T04:00:00+00:00
2008-03-29T04:30:00+00:00
2008-03-29T05:00:00+00:00
2008-03-29T05:30:00+00:00
2008-03-29T06:00:00+00:00
2008-03-29T06:30:00+00:00
2008-03-29T07:00:00+00:00
2008-03-29T07:30:00+00:00
2008-03-29T08:00:00+00:00
2008-03-29T08:47:00+00:00
2008-03-29T09:30:00+00:00
2008-03-29T10:00:00+00:00
2008-03-29T10:30:00+00:00
2008-03-29T11:00:00+00:00
2008-03-29T11:30:00+00:00
2008-03-29T12:00:00+00:00
2008-03-29T12:30:00+00:00
2008-03-29T13:00:00+00:00
2008-03-29T13:30:00+00:00
2008-03-29T14:00:00+00:00
2008-03-29T14:30:00+00:00
2008-03-29T15:00:00+00:00
2008-03-29T15:30:00+00:00
2008-03-29T16:00:00+00:00
2008-03-29T16:30:00+00:00
2008-03-29T17:00:00+00:00
2008-03-29T17:30:00+00:00
2008-03-29T18:00:00+00:00
2008-03-29T18:30:00+00:00
2008-03-29T19:00:00+00:00
2008-03-29T19:30:00+00:00
2008-03-29T20:00:00+00:00
2008-03-29T20:30:00+00:00
2008-03-29T21:00:00+00:00
2008-03-29T21:30:00+00:00
2008-03-29T22:00:00+00:00
2008-03-29T22:30:00+00:00
2008-03-29T23:00:00+00:00
2008-03-29T23:30:00+00:00
2008-03-03T00:00:00+00:00
2008-03-30T03:00:00+00:00
2008-03-30T10:00:00+00:00
2008-03-30T13:00:00+00:00
2008-03-30T20:00:00+00:00
2008-03-30T23:00:00+00:00
2008-03-30T03:00:00+00:00
2008-03-30T03:30:00+00:00
2008-03-30T04:00:00+00:00
2008-03-30T04:30:00+00:00
2008-03-30T05:00:00+00:00
2008-03-30T05:30:00+00:00
2008-03-30T06:00:00+00:00
2008-03-30T06:30:00+00:00
2008-03-30T07:00:00+00:00
2008-03-30T07:30:00+00:00
2008-03-30T08:00:00+00:00
2008-03-30T08:30:00+00:00
2008-03-30T09:00:00+00:00
2008-03-30T09:30:00+00:00
2008-03-30T10:00:00+00:00
2008-03-30T10:30:00+00:00
2008-03-30T11:00:00+00:00
2008-03-30T11:30:00+00:00
2008-03-30T12:00:00+00:00
2008-03-30T12:30:00+00:00
2008-03-30T13:00:00+00:00
2008-03-30T13:30:00+00:00
2008-03-30T14:00:00+00:00
2008-03-30T14:30:00+00:00
2008-03-30T15:00:00+00:00
2008-03-30T15:30:00+00:00
2008-03-30T16:00:00+00:00
2008-03-30T16:30:00+00:00
2008-03-30T17:00:00+00:00
2008-03-30T17:30:00+00:00
2008-03-30T18:00:00+00:00

In [ ]:
print(df.columns)

Index(['DeploymentId', 'date', 'time', 'lon', 'lat', 'Temp_5m', 'pCO2_5m',
       'O2_5m', 'Temp_34point5m', 'pCO2_34point5m', 'O2_34point5m', 'Temp_50m',
       'pCO2_50m', 'O2_50m', 'Temp_75m', 'pCO2_75m', 'O2_75m', 'Temp_105m_96m',
       'pCO2_105m_96m', 'O2_105m_96m', 'Temp_1m', 'pH_1m', 'date_str',
       'time_str', 'datetime', 'created_at'],
      dtype='object')

In [ ]:
# Desired columns (including datetime_str assuming it's created as mentioned previously)
chosen_columns = ['created_at', 'pCO2_5m', 'pH_1m', 'Temp_5m']  # Adjust as needed

# Create a new DataFrame with chosen columns
new_df = df[chosen_columns]

# Reorder columns to make 'datetime_str' the first column
data = new_df[['created_at'] + chosen_columns[1:]]  # Select datetime_str first, then the rest

# Print the new DataFrame
print(data)

                    created_at  pCO2_5m   pH_1m  Temp_5m
0    2008-03-09T10:30:00+00:00    316.4  8.1418     5.41
1    2008-03-09T11:00:00+00:00    316.4  8.1418     5.43
2    2008-03-09T11:30:00+00:00    316.2  8.1420     5.43
3    2008-03-09T12:00:00+00:00    316.9  8.1422     5.43
4    2008-03-09T12:30:00+00:00    316.5  8.1427     5.43
..                         ...      ...     ...      ...
814  2008-03-31T17:30:00+00:00    323.4  8.1434     4.29
815  2008-03-31T18:00:00+00:00    323.5  8.1437     4.29
816  2008-03-31T18:30:00+00:00    324.4  8.1438     4.29
817  2008-03-31T19:00:00+00:00    325.0      nd     4.29
818  2008-03-31T19:30:00+00:00    325.1      nd     4.29

[819 rows x 4 columns]

# Data Cleaning

## Removing Missing Values

In [ ]:
# Replace "nd" with NaN
data.replace("nd", float("NaN"), inplace=True)

# Handle missing values
# For example, fill missing values with linear interpolation
#data.interpolate(method='linear', inplace=True)

# Alternatively, to delete rows with missing values:
data.dropna(inplace=True)

# Display the updated dataset
print(data)

                    created_at  pCO2_5m   pH_1m  Temp_5m
0    2008-03-09T10:30:00+00:00    316.4  8.1418     5.41
1    2008-03-09T11:00:00+00:00    316.4  8.1418     5.43
2    2008-03-09T11:30:00+00:00    316.2  8.1420     5.43
3    2008-03-09T12:00:00+00:00    316.9  8.1422     5.43
4    2008-03-09T12:30:00+00:00    316.5  8.1427     5.43
..                         ...      ...     ...      ...
812  2008-03-31T16:30:00+00:00    322.6  8.1430     4.29
813  2008-03-31T17:00:00+00:00    322.7  8.1431     4.29
814  2008-03-31T17:30:00+00:00    323.4  8.1434     4.29
815  2008-03-31T18:00:00+00:00    323.5  8.1437     4.29
816  2008-03-31T18:30:00+00:00    324.4  8.1438     4.29

[817 rows x 4 columns]

    Rolling Averages: By smoothing out short-term fluctuations, rolling averages provide a clearer picture of the underlying trends in the data Anomalies that cause abrupt changes or deviate from these smoothed trends are more easily detectable.

    Differences Between Consecutive Measurements: Differences between consecutive measurements highlight the rate of change in the sensor data. Anomalies that cause sudden spikes or drops in measurements are often reflected in these differences.

In [ ]:
# Convert pH_1m column to numeric data type
data['pH_1m'] = pd.to_numeric(data['pH_1m'], errors='coerce')

# Calculate rolling averages
window_size = 3
data['pCO2_5m_rolling_mean'] = data['pCO2_5m'].rolling(window=window_size).mean()
data['pH_1m_rolling_mean'] = data['pH_1m'].rolling(window=window_size).mean()
data['Temp_5m_rolling_mean'] = data['Temp_5m'].rolling(window=window_size).mean()

# Calculate differences between consecutive measurements
data['pCO2_5m_diff'] = data['pCO2_5m'].diff()
data['pH_1m_diff'] = data['pH_1m'].diff()
data['Temp_5m_diff'] = data['Temp_5m'].diff()

# Display the updated dataset with additional features
print(data.head())

                  created_at  pCO2_5m   pH_1m  Temp_5m  pCO2_5m_rolling_mean  \
0  2008-03-09T10:30:00+00:00    316.4  8.1418     5.41                   NaN
1  2008-03-09T11:00:00+00:00    316.4  8.1418     5.43                   NaN
2  2008-03-09T11:30:00+00:00    316.2  8.1420     5.43            316.333333
3  2008-03-09T12:00:00+00:00    316.9  8.1422     5.43            316.500000
4  2008-03-09T12:30:00+00:00    316.5  8.1427     5.43            316.533333

   pH_1m_rolling_mean  Temp_5m_rolling_mean  pCO2_5m_diff  pH_1m_diff  \
0                 NaN                   NaN           NaN         NaN
1                 NaN                   NaN           0.0      0.0000
2            8.141867              5.423333          -0.2      0.0002
3            8.142000              5.430000           0.7      0.0002
4            8.142300              5.430000          -0.4      0.0005

   Temp_5m_diff
0           NaN
1          0.02
2          0.00
3          0.00
4          0.00

# Prepare the Dataset for ThingSpeak

In [ ]:
new_df.isnull().sum()

created_at    0
pCO2_5m       0
pH_1m         0
date_str      0
Temp_5m       0
dtype: int64

In [ ]:
data_types = new_df.dtypes
print(data_types)

created_at     object
pCO2_5m       float64
pH_1m          object
date_str       object
Temp_5m       float64
dtype: object

In [ ]:
new_df['pH_1m'] = new_df['pH_1m'].replace('nd', np.nan)
new_df['pH_1m'] = new_df['pH_1m'].astype('float64')


# Try to parse the timestamps in 'created_at' assuming a specific format (YYYY-MM-DD HH:MM:SS)
try:
  new_df['created_at'] = pd.to_datetime(df['created_at'])
except ValueError:
  print("Error parsing timestamps. Check the format in 'created_at'.")
  # Handle the error if the format is different (provide options for custom parsing)

In [ ]:
data_types = new_df.dtypes
print(data_types)

created_at    datetime64[ns, UTC]
pCO2_5m                   float64
pH_1m                     float64
Temp_5m                   float64
dtype: object

In [ ]:
new_df.head()

                 created_at  pCO2_5m   pH_1m  Temp_5m
0 2008-03-09 10:30:00+00:00    316.4  8.1418     5.41
1 2008-03-09 11:00:00+00:00    316.4  8.1418     5.43
2 2008-03-09 11:30:00+00:00    316.2  8.1420     5.43
3 2008-03-09 12:00:00+00:00    316.9  8.1422     5.43
4 2008-03-09 12:30:00+00:00    316.5  8.1427     5.43

In [ ]:
format_string = "%Y-%m-%dT%H:%M:%S"  # Replace with ThingSpeak's format
new_df['created_at'] = pd.to_datetime(new_df['created_at'], format=format_string)

In [ ]:
new_df

                   created_at  pCO2_5m   pH_1m  Temp_5m
0   2008-03-09 10:30:00+00:00    316.4  8.1418     5.41
1   2008-03-09 11:00:00+00:00    316.4  8.1418     5.43
2   2008-03-09 11:30:00+00:00    316.2  8.1420     5.43
3   2008-03-09 12:00:00+00:00    316.9  8.1422     5.43
4   2008-03-09 12:30:00+00:00    316.5  8.1427     5.43
..                        ...      ...     ...      ...
814 2008-03-31 17:30:00+00:00    323.4  8.1434     4.29
815 2008-03-31 18:00:00+00:00    323.5  8.1437     4.29
816 2008-03-31 18:30:00+00:00    324.4  8.1438     4.29
817 2008-03-31 19:00:00+00:00    325.0     NaN     4.29
818 2008-03-31 19:30:00+00:00    325.1     NaN     4.29

[819 rows x 4 columns]

from matplotlib import pyplot as plt
new_df['pCO2_5m'].plot(kind='hist', bins=20, title='pCO2_5m')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
new_df['pH_1m'].plot(kind='hist', bins=20, title='pH_1m')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
new_df['Temp_5m'].plot(kind='hist', bins=20, title='Temp_5m')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
new_df.plot(kind='scatter', x='pCO2_5m', y='pH_1m', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
new_df.plot(kind='scatter', x='pH_1m', y='Temp_5m', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['created_at']
  ys = series['pCO2_5m']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = new_df.sort_values('created_at', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('created_at')
_ = plt.ylabel('pCO2_5m')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['created_at']
  ys = series['pH_1m']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = new_df.sort_values('created_at', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('created_at')
_ = plt.ylabel('pH_1m')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['created_at']
  ys = series['Temp_5m']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = new_df.sort_values('created_at', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('created_at')
_ = plt.ylabel('Temp_5m')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['created_at']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'created_at'}, axis=1)
              .sort_values('created_at', ascending=True))
  xs = counted['created_at']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = new_df.sort_values('created_at', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('created_at')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
new_df['pCO2_5m'].plot(kind='line', figsize=(8, 4), title='pCO2_5m')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
new_df['pH_1m'].plot(kind='line', figsize=(8, 4), title='pH_1m')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
new_df['Temp_5m'].plot(kind='line', figsize=(8, 4), title='Temp_5m')
plt.gca().spines[['top', 'right']].set_visible(False)

In [ ]:
import pandas as pd

# Assuming 'df' is your DataFrame
duplicates = new_df[new_df['created_at'].duplicated()]
print(duplicates)  # This will display rows with duplicate timestamps

new_df.drop_duplicates(subset='created_at', inplace=True)

                   created_at  pCO2_5m   pH_1m  Temp_5m
33  2008-03-10 03:00:00+00:00    316.6  8.1368     5.51
47  2008-03-10 10:00:00+00:00    318.4  8.1379     5.49
53  2008-03-10 13:00:00+00:00    319.8  8.1403     5.51
67  2008-03-10 20:00:00+00:00    318.3  8.1377     5.54
73  2008-03-10 23:00:00+00:00    317.1  8.1389     5.54
..                        ...      ...     ...      ...
771 2008-03-30 20:00:00+00:00    317.4  8.1450     4.34
777 2008-03-30 23:00:00+00:00    317.1  8.1429     4.32
785 2008-03-31 03:00:00+00:00    317.3  8.1443     4.29
799 2008-03-31 10:00:00+00:00    320.7  8.1430     4.32
805 2008-03-31 13:00:00+00:00    321.5  8.1422     4.32

[77 rows x 4 columns]

In [ ]:
new_df.head(12)

                  created_at  pCO2_5m   pH_1m  Temp_5m
0  2008-03-09 10:30:00+00:00    316.4  8.1418     5.41
1  2008-03-09 11:00:00+00:00    316.4  8.1418     5.43
2  2008-03-09 11:30:00+00:00    316.2  8.1420     5.43
3  2008-03-09 12:00:00+00:00    316.9  8.1422     5.43
4  2008-03-09 12:30:00+00:00    316.5  8.1427     5.43
5  2008-03-09 13:00:00+00:00    316.4  8.1433     5.43
6  2008-03-09 13:30:00+00:00    316.6  8.1425     5.43
7  2008-03-09 14:00:00+00:00    315.6  8.1416     5.46
8  2008-03-09 14:30:00+00:00    316.7  8.1417     5.43
9  2008-03-09 15:00:00+00:00    316.3  8.1419     5.46
10 2008-03-09 15:30:00+00:00    316.3  8.1427     5.46
11 2008-03-09 16:00:00+00:00    316.5  8.1435     5.46

In [ ]:
new_df.iloc[33]

created_at    2008-03-10 03:00:00+00:00
pCO2_5m                           316.6
pH_1m                            8.1368
Temp_5m                            5.51
Name: 33, dtype: object

In [ ]:
# Dictionary to map old names to new names
new_names = {'pCO2_5m': 'field1', 'pH_1m': 'field2', 'Temp_5m': 'field3'}

# Rename columns using the dictionary
new_df = new_df.rename(columns=new_names)

# Now 'df_renamed' has your DataFrame with the updated column names
print(new_df)

                   created_at  field1  field2  field3
0   2008-03-09 10:30:00+00:00   316.4  8.1418    5.41
1   2008-03-09 11:00:00+00:00   316.4  8.1418    5.43
2   2008-03-09 11:30:00+00:00   316.2  8.1420    5.43
3   2008-03-09 12:00:00+00:00   316.9  8.1422    5.43
4   2008-03-09 12:30:00+00:00   316.5  8.1427    5.43
..                        ...     ...     ...     ...
814 2008-03-31 17:30:00+00:00   323.4  8.1434    4.29
815 2008-03-31 18:00:00+00:00   323.5  8.1437    4.29
816 2008-03-31 18:30:00+00:00   324.4  8.1438    4.29
817 2008-03-31 19:00:00+00:00   325.0     NaN    4.29
818 2008-03-31 19:30:00+00:00   325.1     NaN    4.29

[742 rows x 4 columns]

In [ ]:
# Choose a filename
filename = 'MAPCO2.csv'

# Save 'new_df' as a CSV file in Colab's environment
new_df.to_csv(filename)

from google.colab import files

# Download the saved CSV file
files.download(filename)